version: '3.0'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - 8000:8000
    volumes:
        - ./Final_Django-main/core:/app
    depends_on:
      - db 
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: django-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahulosho