# Generated by Django 4.2.4 on 2023-11-07 08:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=520, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=520, unique=True, verbose_name='Category safe URL')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sellbook.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='sell_old_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('slug', models.SlugField(max_length=520)),
                ('title', models.CharField(help_text='Required', max_length=520, null=True, verbose_name='Name')),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99'}}, help_text='Maximum 9999.99', max_digits=6, verbose_name='Regular Price')),
                ('discount_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99'}}, help_text='Maximum 9999.99', max_digits=6, verbose_name='Discount price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 100% just type the number of percent '}}, help_text='100%', max_digits=5, verbose_name='Discount percentage')),
                ('image1', models.ImageField(default='old_books/default.png', help_text='Upload a product image', upload_to='old_books/', verbose_name='image1')),
                ('image2', models.ImageField(default='old_books/default.png', help_text='Upload a product image', upload_to='old_books/', verbose_name='image2')),
                ('image3', models.ImageField(default='old_books/default.png', help_text='Upload a product image', upload_to='old_books/', verbose_name='image3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('real_quantity', models.IntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('published', 'published'), ('Sold', 'Sold')], default='published', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sellbook.category')),
                ('selling_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderitem')),
                ('selling_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='orders.order')),
            ],
        ),
    ]
