# Generated by Django 4.2.7 on 2023-12-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField(verbose_name='Return Reason')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Return Date')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_policy', to='orders.order')),
            ],
        ),
    ]
